# Generated by Django 4.2 on 2023-06-15 11:49

import account.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=account.models.CustomDateTimeField(default=datetime.datetime(2023, 6, 15, 11, 49, 48, tzinfo=datetime.timezone.utc)),
        ),
    ]
