# Generated by Django 4.2 on 2023-07-19 06:01

import account.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=account.models.CustomDateTimeField(default=datetime.datetime(2023, 7, 19, 6, 1, 50, tzinfo=datetime.timezone.utc)),
        ),
    ]
