# Generated by Django 4.2 on 2023-07-19 06:11

import account.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_useraccount_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=account.models.CustomDateTimeField(default=datetime.datetime(2023, 7, 19, 6, 11, 30, tzinfo=datetime.timezone.utc)),
        ),
    ]
