# Generated by Django 4.2 on 2023-07-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
